[package]
name = "electorium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better_any = { version = "0.2.0", features = ["derive"] }
blake2 = "0.10.6"